CREATE DATABASE IF NOT EXISTS holiwebsite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE holiwebsite;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    score INT NOT NULL DEFAULT 0,
    photo LONGTEXT NULL,
    created_at VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
